interface HomePage_Params {
    message?: string;
    array?: Array<ExerciseplanEntity>;
}
let __generate__Id: number = 0;
function generateId(): string {
    return "HomePage_" + ++__generate__Id;
}
class HomePage extends View {
    constructor(compilerAssignedUniqueChildId, parent, params, localStorage) {
        super(compilerAssignedUniqueChildId, parent, localStorage);
        this.__message = new ObservedPropertySimple('我是首页', this, "message");
        this.__array = new ObservedPropertyObject([
            { name: "跑步", msg: "长跑、中长跑、短跑" },
            { name: "跑步", msg: "长跑、中长跑、短跑" },
            { name: "跑步", msg: "长跑、中长跑、短跑" },
            { name: "跑步", msg: "长跑、中长跑、短跑" }
        ]
        /**
         * In low-code mode, do not add anything to the build function, as it will be
         * overwritten by the content generated by the .visual file in the build phase.
         */
        , this, "array");
        this.updateWithValueParams(params);
    }
    updateWithValueParams(params: HomePage_Params) {
        if (params.message !== undefined) {
            this.message = params.message;
        }
        if (params.array !== undefined) {
            this.array = params.array;
        }
    }
    aboutToBeDeleted() {
        this.__message.aboutToBeDeleted();
        this.__array.aboutToBeDeleted();
        SubscriberManager.Get().delete(this.id());
    }
    private __message: ObservedPropertySimple<string>;
    get message() {
        return this.__message.get();
    }
    set message(newValue: string) {
        this.__message.set(newValue);
    }
    private __array: ObservedPropertyObject<Array<ExerciseplanEntity>>;
    get array() {
        return this.__array.get();
    }
    set array(newValue: Array<ExerciseplanEntity>) {
        this.__array.set(newValue);
    }
    /**
     * In low-code mode, do not add anything to the build function, as it will be
     * overwritten by the content generated by the .visual file in the build phase.
     */
    render() {
    }
}
export class ExerciseplanEntity {
    constructor(public name: string, public msg: string) {
        this.name = name;
        this.msg = msg;
    }
}
loadDocument(new HomePage("1", undefined, {}));
