interface Wisecare_Params {
    message?: string;
}
let __generate__Id: number = 0;
function generateId(): string {
    return "wisecare_" + ++__generate__Id;
}
import router from '@ohos.router';
class Wisecare extends View {
    constructor(compilerAssignedUniqueChildId, parent, params, localStorage) {
        super(compilerAssignedUniqueChildId, parent, localStorage);
        this.__message = new ObservedPropertySimple('Hello World', this, "message");
        this.updateWithValueParams(params);
    }
    updateWithValueParams(params: Wisecare_Params) {
        if (params.message !== undefined) {
            this.message = params.message;
        }
    }
    aboutToBeDeleted() {
        this.__message.aboutToBeDeleted();
        SubscriberManager.Get().delete(this.id());
    }
    private __message: ObservedPropertySimple<string>;
    get message() {
        return this.__message.get();
    }
    set message(newValue: string) {
        this.__message.set(newValue);
    }
    render() {
        Column.create();
        Column.width("100%");
        Column.height("100%");
        Flex.create({ justifyContent: FlexAlign.Start, alignContent: FlexAlign.Start });
        Flex.width("100%");
        Flex.height("100%");
        Tabs.create({ barPosition: BarPosition.End });
        Tabs.width("100%");
        Tabs.height("100%");
        TabContent.create();
        TabContent.tabBar({ icon: $r('app.media.shouye'), text: "主页" });
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("100%");
        Flex.height("100%");
        Text.create("主页\n");
        Text.width("100%");
        Text.height("5%");
        Text.textAlign(TextAlign.Center);
        Text.fontSize("25fp");
        Text.pop();
        Search.create({ value: "你想搜索些什么" });
        Search.width("100%");
        Search.height("40vp");
        Search.pop();
        Flex.create();
        Flex.width("100%");
        Flex.height("20%");
        Image.create($r('app.media.img_17'));
        Image.width("100%");
        Image.height("100%");
        Flex.pop();
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("100%");
        Flex.height("20%");
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("25%");
        Flex.height("50%");
        Image.create($r('app.media.shenghuofuwu'));
        Image.width("100%");
        Image.height("60%");
        Image.objectFit(ImageFit.Contain);
        Text.create("生活服务\n");
        Text.width("100%");
        Text.height("40%");
        Text.textAlign(TextAlign.Center);
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("25%");
        Flex.height("50%");
        Image.create($r('app.media.huli'));
        Image.width("100%");
        Image.height("60%");
        Image.objectFit(ImageFit.Contain);
        Text.create("护理用品");
        Text.width("100%");
        Text.height("40%");
        Text.textAlign(TextAlign.Center);
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("25%");
        Flex.height("50%");
        Image.create($r('app.media.jiankong'));
        Image.width("100%");
        Image.height("60%");
        Image.objectFit(ImageFit.Contain);
        Text.create("视频监管");
        Text.width("100%");
        Text.height("40%");
        Text.textAlign(TextAlign.Center);
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("25%");
        Flex.height("50%");
        Image.create($r('app.media.yuyue'));
        Image.width("100%");
        Image.height("60%");
        Image.objectFit(ImageFit.Contain);
        Text.create("预约挂号\n");
        Text.width("100%");
        Text.height("40%");
        Text.textAlign(TextAlign.Center);
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("25%");
        Flex.height("50%");
        Image.create($r('app.media.teeth1'));
        Image.width("100%");
        Image.height("60%");
        Image.objectFit(ImageFit.Contain);
        Text.create("口腔齿科");
        Text.width("100%");
        Text.height("40%");
        Text.textAlign(TextAlign.Center);
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("25%");
        Flex.height("50%");
        Image.create($r('app.media.banjia'));
        Image.width("100%");
        Image.height("60%");
        Image.objectFit(ImageFit.Contain);
        Text.create("搬家\n");
        Text.width("100%");
        Text.height("40%");
        Text.textAlign(TextAlign.Center);
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("25%");
        Flex.height("50%");
        Image.create($r('app.media.xiyiji'));
        Image.width("100%");
        Image.height("60%");
        Image.objectFit(ImageFit.Contain);
        Text.create("洗衣");
        Text.width("100%");
        Text.height("40%");
        Text.textAlign(TextAlign.Center);
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("25%");
        Flex.height("50%");
        Image.create($r('app.media.gongyi'));
        Image.width("100%");
        Image.height("60%");
        Image.objectFit(ImageFit.Contain);
        Text.create("一键求助");
        Text.width("100%");
        Text.height("40%");
        Text.textAlign(TextAlign.Center);
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        Flex.pop();
        Text.create();
        Text.width("100%");
        Text.height("15vp");
        Text.pop();
        Flex.create();
        Flex.width("100%");
        Flex.height("20%");
        Image.create($r('app.media.120'));
        Image.width("50%");
        Image.height("100%");
        Image.create($r('app.media.shangdian'));
        Image.width("50%");
        Image.height("100%");
        Flex.pop();
        Text.create();
        Text.width("100%");
        Text.height("15vp");
        Text.pop();
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("100%");
        Flex.height("25%");
        Flex.create({ wrap: FlexWrap.NoWrap });
        Image.create($r('app.media.remen'));
        Image.width("10%");
        Image.height("20%");
        Text.create("   热门推荐");
        Text.width("100%");
        Text.height("20%");
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        Image.create($r('app.media.huanyaohuli'));
        Image.width("25%");
        Image.height("70%");
        Image.create($r('app.media.jingzhuihuili'));
        Image.width("25%");
        Image.height("70%");
        Image.create($r('app.media.shangmenfuwu'));
        Image.width("25%");
        Image.height("70%");
        Image.create($r('app.media.laorenpeihu'));
        Image.width("25%");
        Image.height("70%");
        Flex.pop();
        Flex.pop();
        TabContent.pop();
        TabContent.create();
        TabContent.tabBar({ icon: $r('app.media.fenlei'), text: "分类" });
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("100%");
        Flex.height("100%");
        Text.create("分类");
        Text.width("100%");
        Text.height("5%");
        Text.textAlign(TextAlign.Center);
        Text.fontSize("25fp");
        Text.pop();
        Tabs.create();
        Tabs.width("100%");
        Tabs.height("95%");
        Tabs.vertical(false);
        Tabs.barMode(BarMode.Scrollable);
        TabContent.create();
        TabContent.constraintSize({ minWidth: "0%" });
        TabContent.tabBar({ text: "老年服务" });
        List.create();
        List.width("100%");
        List.height("92%");
        ListItem.create();
        ListItem.width("100%");
        ListItem.height("20%");
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("100%");
        Flex.height("100%");
        Image.create($r('app.media.img_28'));
        Image.width("40%");
        Image.height("100%");
        Image.objectFit(ImageFit.Cover);
        Text.create("家政保洁");
        Text.width("40%");
        Text.height("60%");
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        ListItem.pop();
        ListItem.create();
        ListItem.width("100%");
        ListItem.height("20%");
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("100%");
        Flex.height("100%");
        Image.create($r('app.media.img_27'));
        Image.width("40%");
        Image.height("100%");
        Image.objectFit(ImageFit.Cover);
        Text.create("居家保洁");
        Text.width("200vp");
        Text.height("60vp");
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        ListItem.pop();
        ListItem.create();
        ListItem.width("100%");
        ListItem.height("100%");
        ListItem.pop();
        ListItem.create();
        ListItem.width("100%");
        ListItem.height("20vp");
        ListItem.pop();
        List.pop();
        TabContent.pop();
        TabContent.create();
        TabContent.tabBar({ text: "家庭医生" });
        List.create();
        List.width("100%");
        List.height("90%");
        ListItem.create();
        ListItem.width("100%");
        ListItem.height("20%");
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("100%");
        Flex.height("100%");
        Image.create($r('app.media.img_29'));
        Image.width("30%");
        Image.height("100%");
        Text.create("姓名：\n职能：医生");
        Text.width("200vp");
        Text.height("60vp");
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        ListItem.pop();
        ListItem.create();
        ListItem.width("100%");
        ListItem.height("20%");
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("100%");
        Flex.height("100%");
        Image.create($r('app.media.img_30'));
        Image.width("30%");
        Image.height("100%");
        Image.objectFit(ImageFit.Contain);
        Text.create("姓名：\n职能：护士");
        Text.width("200vp");
        Text.height("60vp");
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        ListItem.pop();
        ListItem.create();
        ListItem.width("100%");
        ListItem.height("20%");
        ListItem.pop();
        ListItem.create();
        ListItem.width("100%");
        ListItem.height("20vp");
        ListItem.pop();
        ListItem.create();
        ListItem.width("100%");
        ListItem.height("20%");
        ListItem.pop();
        ListItem.create();
        ListItem.width("100%");
        ListItem.height("20%");
        ListItem.pop();
        List.pop();
        TabContent.pop();
        TabContent.create();
        TabContent.tabBar({ text: "社区养老" });
        TabContent.pop();
        TabContent.create();
        TabContent.tabBar({ text: "机构养老" });
        TabContent.pop();
        TabContent.create();
        TabContent.tabBar({ text: "邮政物流" });
        Flex.create();
        Flex.width("100%");
        Flex.height("92%");
        Flex.pop();
        TabContent.pop();
        TabContent.create();
        TabContent.tabBar({ text: "老年餐厅" });
        TabContent.pop();
        Tabs.pop();
        Flex.create();
        Flex.pop();
        Flex.pop();
        TabContent.pop();
        TabContent.create();
        TabContent.tabBar({ icon: $r('app.media.faxian'), text: "发现" });
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("100%");
        Flex.height("100%");
        Flex.margin({ top: "0vp", bottom: "0vp", left: "0vp", right: "0vp" });
        Text.create("发现");
        Text.width("100%");
        Text.height("5%");
        Text.textAlign(TextAlign.Center);
        Text.fontSize("25fp");
        Text.pop();
        Flex.create({ direction: FlexDirection.Row, wrap: FlexWrap.Wrap });
        Flex.width("100%");
        Flex.height("25%");
        Image.create($r('app.media.faxiantu'));
        Image.width("100%");
        Image.height("100%");
        Image.alignSelf(ItemAlign.Auto);
        Image.objectFit(ImageFit.Cover);
        Image.renderMode(ImageRenderMode.Original);
        Button.createWithLabel("添加长者");
        Button.width("50%");
        Button.height("25%");
        Button.offset({ x: "85vp", y: "-130vp" });
        Button.backgroundColor("#969e57");
        Button.fontSize("30fp");
        Button.fontStyle(FontStyle.Normal);
        Button.onClick(() => {
            router.pushUrl({
                url: "pages/OlderPage"
            });
        });
        Button.pop();
        Flex.pop();
        Flex.create();
        Flex.width("100%");
        Flex.height("70%");
        Navigation.create();
        Navigation.width("100%");
        Navigation.height("90%");
        Navigation.title("           附近的养老院");
        Navigation.subTitle("                           更多");
        Navigation.titleMode(NavigationTitleMode.Mini);
        Navigation.hideToolBar(false);
        Navigation.hideTitleBar(false);
        Image.create($r('app.media.ditu'));
        Image.width("100%");
        Image.height("100%");
        Navigation.pop();
        Flex.pop();
        Flex.pop();
        TabContent.pop();
        TabContent.create();
        TabContent.tabBar({ icon: $r('app.media.me'), text: "我的" });
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("100%");
        Flex.height("100%");
        Text.create("个人中心");
        Text.width("100%");
        Text.height("5%");
        Text.textAlign(TextAlign.Center);
        Text.fontSize("25fp");
        Text.pop();
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("100%");
        Flex.height("10%");
        Image.create($r('app.media.touxiang'));
        Image.width("25%");
        Image.height("100%");
        Image.objectFit(ImageFit.Contain);
        Text.create("衡骏杰");
        Text.width("15%");
        Text.height("30%");
        Text.fontSize("15fp");
        Text.pop();
        Image.create($r('app.media.erweima1'));
        Image.width("60%");
        Image.height("40%");
        Image.objectFit(ImageFit.Contain);
        Image.create($r('app.media.shezhi'));
        Image.width("60%");
        Image.height("40%");
        Image.offset({ x: "148.7vp", y: "-31.33vp" });
        Image.objectFit(ImageFit.Contain);
        Image.renderMode(ImageRenderMode.Template);
        Flex.pop();
        Text.create();
        Text.width("100%");
        Text.height("5%");
        Text.pop();
        Flex.create();
        Flex.width("100%");
        Flex.height("15%");
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("25%");
        Flex.height("100%");
        Image.create($r('app.media.jigou'));
        Image.width("100%");
        Image.height("60%");
        Image.objectFit(ImageFit.Contain);
        Text.create("我的机构");
        Text.width("100%");
        Text.height("40%");
        Text.textAlign(TextAlign.Center);
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("25%");
        Flex.height("100%");
        Image.create($r('app.media.xiaoxi'));
        Image.width("100%");
        Image.height("60%");
        Image.objectFit(ImageFit.Contain);
        Text.create("我的消息");
        Text.width("100%");
        Text.height("40%");
        Text.textAlign(TextAlign.Center);
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("25%");
        Flex.height("100%");
        Image.create($r('app.media.shebei'));
        Image.width("100%");
        Image.height("60%");
        Image.objectFit(ImageFit.Contain);
        Text.create("我的设施");
        Text.width("100%");
        Text.height("40%");
        Text.textAlign(TextAlign.Center);
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("25%");
        Flex.height("100%");
        Image.create($r('app.media.huodong'));
        Image.width("100%");
        Image.height("60%");
        Image.objectFit(ImageFit.Contain);
        Text.create("我的活动");
        Text.width("100%");
        Text.height("40%");
        Text.textAlign(TextAlign.Center);
        Text.fontSize("15fp");
        Text.pop();
        Flex.pop();
        Flex.pop();
        Text.create();
        Text.width("100%");
        Text.height("3%");
        Text.pop();
        Flex.create();
        Flex.width("100%");
        Flex.height("10%");
        Text.create("我的健康");
        Text.width("60%");
        Text.height("60%");
        Text.fontSize("25fp");
        Text.fontStyle(FontStyle.Italic);
        Text.pop();
        Search.create({ value: "查看我的健康" });
        Search.width("100%");
        Search.height("40%");
        Search.onClick(() => {
            router.pushUrl({ url: 'pages/ExercisePlan' });
        });
        Search.pop();
        Flex.pop();
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("100%");
        Flex.height("25%");
        Text.create("我的亲友");
        Text.width("30%");
        Text.height("30%");
        Text.fontSize("25fp");
        Text.pop();
        Flex.create({ wrap: FlexWrap.Wrap });
        Flex.width("100%");
        Flex.height("70%");
        Image.create($r('app.media.jia1'));
        Image.width("15%");
        Image.height("40%");
        Image.objectFit(ImageFit.Contain);
        Image.renderMode(ImageRenderMode.Template);
        Text.create("   添加");
        Text.width("200vp");
        Text.height("60vp");
        Text.textAlign(TextAlign.Start);
        Text.fontSize("12fp");
        Text.pop();
        Button.createWithLabel("管理亲友");
        Button.width("140vp");
        Button.height("40vp");
        Button.borderColor("#931f1f");
        Button.backgroundColor("#e5dcdc");
        Button.fontColor("#e88f5e");
        Button.margin({ top: "20vp", left: "100vp" });
        Button.pop();
        Flex.pop();
        Flex.pop();
        Flex.create();
        Flex.width("100%");
        Flex.height("20%");
        Button.createWithLabel("退出登录");
        Button.width("160vp");
        Button.height("40vp");
        Button.margin({ top: "50vp", left: "90vp" });
        Button.fontSize("16fp");
        Button.onClick(this.onTestClick.bind(this));
        Button.pop();
        Flex.pop();
        Flex.pop();
        TabContent.pop();
        Tabs.pop();
        Flex.pop();
        Column.pop();
    }
    onTestClick() {
        router.pushUrl({
            url: "pages/login",
        });
    }
}
loadDocument(new Wisecare("1", undefined, {}));
