

export interface  DataInfinity{
  id:string
  name:string
  GoodNum:string

}

export const DataInfinity_TestData: Array<DataInfinity> = [
  {
    "id": '1',
    "name": '苹果',
    "GoodNum": '114514'

  },
  {
    "id": '2',
    "name": '葡萄',
    "GoodNum": '19198'

  },
  {
    "id": '3',
    "name": '西瓜',
    "GoodNum": '9801'

  },
  {
    "id": '4',
    "name": '香蕉',
    "GoodNum": '8431'

  },
  {
    "id": '5',
    "name": '菠萝',
    "GoodNum": '7546'

  },
  {
    "id": '6',
    "name": '榴莲',
    "GoodNum": '7431'

  }
]

export const DataInfinity_TestData2 : Array<DataInfinity> = [
  {
    "id": '1',
    "name": '榴莲',
    "GoodNum": '114514'

  },
  {
    "id": '2',
    "name": '菠萝',
    "GoodNum": '19198'

  },
  {
    "id": '3',
    "name": '香蕉',
    "GoodNum": '9801'

  },
  {
    "id": '4',
    "name": '西瓜',
    "GoodNum": '8431'

  },
  {
    "id": '5',
    "name": '葡萄',
    "GoodNum": '7546'

  },
  {
    "id": '6',
    "name": '苹果',
    "GoodNum": '7431'

  }
]