/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Common constants for common component.
 */
export class CommonConstants {
  // Font family.
  static readonly HARMONY_HEI_TI_FONT_FAMILY = 'HarmonyHeiTi';

  // 100 percent.
  static readonly FULL_PERCENT: string = '100%';

  // 50 percent.
  static readonly PERCENT_50: string = '50%';

  // Duration.
  static readonly TOAST_DURATION: number = 2000;

  // Space.
  static readonly NORMAL_SPACE: number = 12;
}